# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
arch: arm64
os: linux

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install pytest     
  - pip install pycparser
  - python setup.py build_ext -f -i

script:
  - py.test c/ testing/

notifications:
  # Perhaps we should have status emails sent to the mailing list, but
  # let's wait to see what people think before turning that on.
  email: false
