arch: arm64
os: linux
language: python
services:
  - docker
script:
  - python -m pip install --upgrade pip
  #- pip install cibuildwheel==0.12.0
  - pip install git+https://github.com/joerick/cibuildwheel.git
  - CIBW_MANYLINUX_AARCH64_IMAGE=manylinux2014 CIBW_TEST_REQUIRES=pytest CIBW_TEST_COMMAND='python -m pytest {project}/c {project}/testing' cibuildwheel --output-dir wheelhouse .
